version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  mico-msg-pipe-node:
    lang: node
    handler: ./mico-msg-pipe-node
    image: zwickel/mico-msg-pipe-node:latest

